/* Genereert een popup ('Splash Screen') met animated gif en close-button bij binnenkomst op de website. GIF toont toelichting bij het gebruik van de drag&drop functionaliteit icm kaartlagen-CSV's.*/
d3.select('body').append('div')
.attr('id','toelichtingSplashScreen')
.style('z-index',40000)
.style('position','absolute')
.style('top','50%')
.style('left','50%')
.style('background-color','#E3F5FF')
.style('width','754px')
.style('height','435px')
.style('margin-top','-255px')
.style('margin-left','-377px')
.style('border-radius','10px')
.style('border','2px solid black')
.style('padding','0px')
.append('svg')
  .style('z-index',8000)
  .style('position','absolute')
  .style('top','400px')
  .style('left','20px')
  .style('width',800).style('height',60)
  .attr('id','buttonsvg')
  .attr('pointer-events', 'all')

d3.select('#buttonsvg').append('rect')
  .attr('id','buttonCloseToelichting')
  .attr('width',100)
  .attr('height',50)
  .style('stroke','black')
  .style('stroke-width',2)
  .attr('rx',5).attr('ry',5)
  .attr('x',300)
  .attr('y',2)
  .attr('fill','white') 
  .style('pointer-events','all')
d3.select('#buttonsvg').append('text')
  .attr('id','closeButtonText')
  .style('font-family', 'RijksoverheidSans').style('font-size', 30+'px').style('font-weight',200)
  .attr('y',36).attr('x',330)
  .style('pointer-events','none')
  .text('OK')

d3.select('#toelichtingSplashScreen').append('img').attr('id', 'example1').attr('src', './src/gif/kaartlagencsvtoelichting.gif').attr('width','750px').style('position','absolute').style('top','5px');

d3.select('#buttonCloseToelichting')
.on('mouseover',function(){d3.select('#closeButtonText').attr('fill','white'); d3.select(this).attr('fill','#265A8B')})
.on('mouseout',function(){d3.select('#closeButtonText').attr('fill','black'); d3.select(this).attr('fill','#e5eff5')})
.on('click',function(){
    console.log('aht')
    d3.select('#toelichtingSplashScreen').remove();
    d3.select(this).remove();
  })